GET http://localhost:8000/api/products

###
GET http://localhost:8000/api/products/621c77871cb469762ecb926a

###
### get by brand
GET http://localhost:8000/api/products/brand/adidas

###
POST http://localhost:8000/api/products
content-type:application/json

{
    "productName":"hoodie1",
    "productShortDesc":"avengers hoodie1",
    "images":"images1",
    "slug" : "",
    "brand" : "62206e433e306f93d16588f8",
    "featured" : "",
    "cateogary" : [""],
    "productContent" : "",
    "metaName" : "",
    "metaKeyword" : "",
    "metaDescription" : "",
    "stock":[
        {
            "quantity":5,
            "attribute":["red","small"],
            "price":100
        },
        {
            "quantity":10,
            "attribute":["red","medium"],
            "price":200
        },
        {
            "quantity":5,
            "attribute":["blue","small"],
            "price":100
        },
        {
            "quantity":10,
            "attribute":["blue","medium"],
            "price":200
        }
    ],
    "attributeDetails" :[
        {
            "attributeName" : "colour",
            "attributes" : ["red","blue"]
        },
        {
            "attributeName" : "size",
            "attributes" : ["s","m"]
        }
    ],
    "discountType":"percentage"
}

###

